# Sverchok Spotlight - grandMA Export Node
# Generates grandMA2 and grandMA3 patch commands, 3D coordinates, and macro XML files

import math
import uuid
import bpy
from bpy.props import StringProperty, EnumProperty, BoolProperty
from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode as update_node

def safe_float(v, default=0.0):
    """Safely converts a value to float."""
    try:
        if isinstance(v, (list, tuple)):
            return float(v[0]) if len(v) > 0 else default
        return float(v)
    except (ValueError, TypeError):
        return default

def get_fixture_coords(fix):
    """Safely extracts (x, y, z) 3D coordinate floats from fixture dictionary."""
    for key in ['world_pos', 'location', 'coords', 'target', 'position']:
        val = fix.get(key)
        if isinstance(val, (list, tuple)) and len(val) >= 3:
            try:
                return (safe_float(val[0]), safe_float(val[1]), safe_float(val[2]))
            except Exception:
                pass
    return (0.0, 0.0, 0.0)


class SV_OT_SpotlightGrandMAExport(bpy.types.Operator):
    """Exports grandMA patch script to file and Blender text block"""
    bl_idname = "node.sv_spotlight_grandma_export"
    bl_label = "Export to grandMA"
    bl_options = {'REGISTER'}

    node_name: StringProperty(name="Node Name", default="")
    tree_name: StringProperty(name="Tree Name", default="")

    def execute(self, context):
        try:
            tree = bpy.data.node_groups.get(self.tree_name)
            if not tree:
                self.report({'WARNING'}, f"Node tree '{self.tree_name}' not found.")
                return {'CANCELLED'}
            node = tree.nodes.get(self.node_name)
            if not node:
                self.report({'WARNING'}, f"Node '{self.node_name}' not found.")
                return {'CANCELLED'}

            count, path = node.export_data()
            self.report({'INFO'}, f"grandMA: Exported {count} fixtures to {path}")
            return {'FINISHED'}
        except Exception as e:
            self.report({'ERROR'}, f"grandMA export failed: {e}")
            return {'CANCELLED'}


class SvSpotlightGrandMANode(bpy.types.Node, SverchCustomTreeNode):
    """
    Exports patched fixtures to grandMA2 and grandMA3 console macro formats,
    including DMX addresses, Fixture IDs, and 3D XYZ/Rotation transforms.
    """
    bl_idname = 'SvSpotlightGrandMANode'
    bl_label = 'Spotlight grandMA Export'
    bl_icon = 'OUTLINER_DATA_LIGHT'
    sv_icon = 'SV_COLOR_ROUGHNESS'

    export_format: EnumProperty(
        name="Format",
        description="Target console format",
        items=[
            ('MA3_CLI', "grandMA3 Command Line (.txt)", "Plain command line script for grandMA3"),
            ('MA3_XML', "grandMA3 Macro XML (.xml)", "Importable Macro XML for grandMA3"),
            ('MA2_CLI', "grandMA2 Command Line (.txt)", "Plain command line script for grandMA2"),
            ('MA2_XML', "grandMA2 Macro XML (.xml)", "Native grandMA2 Macro XML import format"),
        ],
        default='MA3_CLI',
        update=update_node
    )

    file_path: StringProperty(
        name="File Path",
        description="Path to save exported file (e.g. C:/temp/rig_patch.xml)",
        default="//grandma_patch.txt",
        subtype='FILE_PATH',
        update=update_node
    )

    create_blender_text: BoolProperty(
        name="Blender Text Block",
        description="Also store export in Blender's internal Text Editor",
        default=True,
        update=update_node
    )

    last_status: StringProperty(
        name="Status",
        default="Ready"
    )

    def sv_init(self, context):
        self.inputs.new('SvStringsSocket', 'Fixtures')
        self.inputs.new('SvStringsSocket', 'File Path').prop_name = 'file_path'

        self.outputs.new('SvStringsSocket', 'Script Text')
        self.outputs.new('SvStringsSocket', 'File Path')
        self.outputs.new('SvStringsSocket', 'Status')

    def draw_buttons(self, context, layout):
        col = layout.column(align=True)
        col.prop(self, 'export_format')
        col.prop(self, 'file_path')
        col.prop(self, 'create_blender_text')

        op = col.operator('node.sv_spotlight_grandma_export', text="Export grandMA Patch", icon='EXPORT')
        op.node_name = self.name
        op.tree_name = self.id_data.name if self.id_data else ""

        col.label(text=self.last_status, icon='INFO')

    def build_script(self, fixtures):
        """Generates script text based on selected console format."""
        lines = []

        if self.export_format == 'MA3_CLI':
            lines.append("# grandMA3 Rig Patch and 3D Setup Script")
            lines.append("# Generated by Sverchok Spotlight")
            lines.append("ClearAll")
            for fix in fixtures:
                fid = int(safe_float(fix.get('unit_number', 1), 1))
                u = int(safe_float(fix.get('universe', 1), 1))
                a = int(safe_float(fix.get('address', 1), 1))
                pos = get_fixture_coords(fix)
                pan = safe_float(fix.get('pan', 0.0), 0.0)
                tilt = safe_float(fix.get('tilt', 0.0), 0.0)

                lines.append(f'Set Fixture {fid} "DMXUniverse" {u} "DMXAddress" {a}')
                lines.append(f'Set Fixture {fid} "PosX" {pos[0]:.3f} "PosY" {pos[1]:.3f} "PosZ" {pos[2]:.3f} "RotY" {tilt:.1f} "RotZ" {pan:.1f}')

        elif self.export_format == 'MA3_XML':
            lines.append('<?xml version="1.0" encoding="UTF-8"?>')
            lines.append('<GMA3 DataVersion="1.9.0">')
            lines.append('  <Macro Name="Spotlight Patch" Guid="' + str(uuid.uuid4()) + '">')
            lines.append('    <Macroline Command="ClearAll" />')
            for fix in fixtures:
                fid = int(safe_float(fix.get('unit_number', 1), 1))
                u = int(safe_float(fix.get('universe', 1), 1))
                a = int(safe_float(fix.get('address', 1), 1))
                pos = get_fixture_coords(fix)
                pan = safe_float(fix.get('pan', 0.0), 0.0)
                tilt = safe_float(fix.get('tilt', 0.0), 0.0)
                cmd = f'Set Fixture {fid} &quot;DMXUniverse&quot; {u} &quot;DMXAddress&quot; {a}'
                lines.append(f'    <Macroline Command="{cmd}" />')
                cmd3d = f'Set Fixture {fid} &quot;PosX&quot; {pos[0]:.3f} &quot;PosY&quot; {pos[1]:.3f} &quot;PosZ&quot; {pos[2]:.3f} &quot;RotY&quot; {tilt:.1f} &quot;RotZ&quot; {pan:.1f}'
                lines.append(f'    <Macroline Command="{cmd3d}" />')
            lines.append('  </Macro>')
            lines.append('</GMA3>')

        elif self.export_format == 'MA2_CLI':
            lines.append("# grandMA2 Rig Patch and 3D Setup Script")
            lines.append("# Generated by Sverchok Spotlight")
            lines.append("ClearAll")
            for fix in fixtures:
                fid = int(safe_float(fix.get('unit_number', 1), 1))
                u = int(safe_float(fix.get('universe', 1), 1))
                a = int(safe_float(fix.get('address', 1), 1))
                pos = get_fixture_coords(fix)
                pan = safe_float(fix.get('pan', 0.0), 0.0)
                tilt = safe_float(fix.get('tilt', 0.0), 0.0)

                lines.append(f'Assign Fixture {fid} At DMX {u}.{a} /nc')
                lines.append(f'Assign Fixture {fid} /3dpos=({pos[0]:.3f}, {pos[1]:.3f}, {pos[2]:.3f}) /3drot=(0.0, {tilt:.1f}, {pan:.1f})')

        elif self.export_format == 'MA2_XML':
            lines.append('<?xml version="1.0" encoding="utf-8"?>')
            lines.append('<MA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.malighting.de/grandma2/xml/MA" major_vers="3" minor_vers="9" stream_vers="60">')
            lines.append('  <Macro index="0" name="Spotlight Rig Patch">')
            idx = 0
            lines.append(f'    <Macroline index="{idx}"><text>ClearAll</text></Macroline>')
            idx += 1
            for fix in fixtures:
                fid = int(safe_float(fix.get('unit_number', 1), 1))
                u = int(safe_float(fix.get('universe', 1), 1))
                a = int(safe_float(fix.get('address', 1), 1))
                pos = get_fixture_coords(fix)
                pan = safe_float(fix.get('pan', 0.0), 0.0)
                tilt = safe_float(fix.get('tilt', 0.0), 0.0)

                patch_cmd = f'Assign Fixture {fid} At DMX {u}.{a} /nc'
                lines.append(f'    <Macroline index="{idx}"><text>{patch_cmd}</text></Macroline>')
                idx += 1
                pos_cmd = f'Assign Fixture {fid} /3dpos=({pos[0]:.3f}, {pos[1]:.3f}, {pos[2]:.3f}) /3drot=(0.0, {tilt:.1f}, {pan:.1f})'
                lines.append(f'    <Macroline index="{idx}"><text>{pos_cmd}</text></Macroline>')
                idx += 1
            lines.append('  </Macro>')
            lines.append('</MA>')

        return "\n".join(lines)

    def export_data(self):
        """Exports data to file and Blender text block."""
        if not self.inputs['Fixtures'].is_linked:
            self.last_status = "No fixtures linked"
            return 0, ""

        raw_in = self.inputs['Fixtures'].sv_get()
        fixtures = []
        if isinstance(raw_in, list):
            for item in raw_in:
                if isinstance(item, list):
                    fixtures.extend([x for x in item if isinstance(x, dict)])
                elif isinstance(item, dict):
                    fixtures.append(item)

        if not fixtures:
            self.last_status = "No fixture dictionaries found"
            return 0, ""

        script_content = self.build_script(fixtures)

        # Write to Blender internal text block
        if self.create_blender_text:
            text_name = "grandMA_patch.txt" if "CLI" in self.export_format else "grandMA_patch.xml"
            txt_block = bpy.data.texts.get(text_name) or bpy.data.texts.new(text_name)
            txt_block.clear()
            txt_block.write(script_content)

        # Write to disk if path is provided
        resolved_path = bpy.path.abspath(self.file_path)
        try:
            with open(resolved_path, 'w', encoding='utf-8') as f:
                f.write(script_content)
            self.last_status = f"Exported {len(fixtures)} fixtures"
        except Exception as e:
            self.last_status = f"Write error: {e}"

        return len(fixtures), resolved_path

    def process(self):
        if not self.inputs['Fixtures'].is_linked:
            return

        raw_in = self.inputs['Fixtures'].sv_get()
        fixtures = []
        if isinstance(raw_in, list):
            for item in raw_in:
                if isinstance(item, list):
                    fixtures.extend([x for x in item if isinstance(x, dict)])
                elif isinstance(item, dict):
                    fixtures.append(item)

        if not fixtures:
            return

        script_text = self.build_script(fixtures)
        resolved_path = bpy.path.abspath(self.file_path)

        self.outputs['Script Text'].sv_set([script_text])
        self.outputs['File Path'].sv_set([resolved_path])
        self.outputs['Status'].sv_set([self.last_status])


def register():
    bpy.utils.register_class(SV_OT_SpotlightGrandMAExport)
    bpy.utils.register_class(SvSpotlightGrandMANode)

def unregister():
    bpy.utils.unregister_class(SvSpotlightGrandMANode)
    bpy.utils.unregister_class(SV_OT_SpotlightGrandMAExport)
