# Fixture profiles and presets for Sverchok Spotlight
# Specifies photometric, electrical, mechanical, and light generator / emitter specs

FIXTURE_PRESETS = {
    "Robe Robin MegaPointe": {
        "name": "Robe Robin MegaPointe",
        "manufacturer": "Robe",
        "type": "Spot / Beam",
        "beam_angle": 1.8,
        "field_angle": 21.0,
        "candela": 2200000.0,
        "weight_kg": 22.0,
        "wattage": 470.0,
        "dmx_footprint": 39,
        "lamp_type": "Discharge 470W",
        "emitter_offset": 0.36,
        "lens_diameter": 0.15,
    },
    "Martin MAC Viper Profile": {
        "name": "Martin MAC Viper Profile",
        "manufacturer": "Martin",
        "type": "Profile Spot",
        "beam_angle": 10.0,
        "field_angle": 44.0,
        "candela": 550000.0,
        "weight_kg": 32.0,
        "wattage": 1000.0,
        "dmx_footprint": 26,
        "lamp_type": "Discharge 1000W",
        "emitter_offset": 0.45,
        "lens_diameter": 0.14,
    },
    "Clay Paky Sharpy": {
        "name": "Clay Paky Sharpy",
        "manufacturer": "Clay Paky",
        "type": "Beam",
        "beam_angle": 0.5,
        "field_angle": 3.8,
        "candela": 1500000.0,
        "weight_kg": 19.0,
        "wattage": 190.0,
        "dmx_footprint": 16,
        "lamp_type": "Platinum 5R",
        "emitter_offset": 0.35,
        "lens_diameter": 0.145,
    },
    "Martin MAC Aura": {
        "name": "Martin MAC Aura",
        "manufacturer": "Martin",
        "type": "Wash",
        "beam_angle": 11.0,
        "field_angle": 58.0,
        "candela": 115000.0,
        "weight_kg": 5.6,
        "wattage": 260.0,
        "dmx_footprint": 14,
        "lamp_type": "LED RGBW",
        "emitter_offset": 0.26,
        "lens_diameter": 0.20,
    },
    "ETC Source Four LED Series 2 (26 deg)": {
        "name": "ETC Source Four LED Series 2 (26 deg)",
        "manufacturer": "ETC",
        "type": "Profile / Leko",
        "beam_angle": 26.0,
        "field_angle": 26.0,
        "candela": 125000.0,
        "weight_kg": 8.3,
        "wattage": 172.0,
        "dmx_footprint": 6,
        "lamp_type": "LED Luxeon",
        "emitter_offset": 0.32,
        "lens_diameter": 0.17,
    },
    "ETC Source Four LED Series 2 (36 deg)": {
        "name": "ETC Source Four LED Series 2 (36 deg)",
        "manufacturer": "ETC",
        "type": "Profile / Leko",
        "beam_angle": 36.0,
        "field_angle": 36.0,
        "candela": 85000.0,
        "weight_kg": 8.3,
        "wattage": 172.0,
        "dmx_footprint": 6,
        "lamp_type": "LED Luxeon",
        "emitter_offset": 0.32,
        "lens_diameter": 0.17,
    },
    "Chauvet COLORado Batten Q15": {
        "name": "Chauvet COLORado Batten Q15",
        "manufacturer": "Chauvet Professional",
        "type": "Batten / Bar",
        "beam_angle": 15.0,
        "field_angle": 42.0,
        "candela": 45000.0,
        "weight_kg": 8.8,
        "wattage": 180.0,
        "dmx_footprint": 14,
        "lamp_type": "LED RGBAW",
        "emitter_offset": 0.18,
        "lens_diameter": 0.10,
    },
    "Generic LED Par RGBW": {
        "name": "Generic LED Par RGBW",
        "manufacturer": "Generic",
        "type": "Par",
        "beam_angle": 25.0,
        "field_angle": 30.0,
        "candela": 35000.0,
        "weight_kg": 3.5,
        "wattage": 120.0,
        "dmx_footprint": 7,
        "lamp_type": "LED RGBW",
        "emitter_offset": 0.22,
        "lens_diameter": 0.18,
    },
    "Generic 1000W Tungsten Profile": {
        "name": "Generic 1000W Tungsten Profile",
        "manufacturer": "Generic",
        "type": "Conventional Profile",
        "beam_angle": 20.0,
        "field_angle": 35.0,
        "candela": 90000.0,
        "weight_kg": 7.0,
        "wattage": 1000.0,
        "dmx_footprint": 1,
        "lamp_type": "Halogen 1000W",
        "emitter_offset": 0.35,
        "lens_diameter": 0.15,
    },
    "Custom": {
        "name": "Custom User Fixture",
        "manufacturer": "Custom",
        "type": "Custom",
        "beam_angle": 20.0,
        "field_angle": 35.0,
        "candela": 100000.0,
        "weight_kg": 15.0,
        "wattage": 300.0,
        "dmx_footprint": 16,
        "lamp_type": "LED / Discharge",
        "emitter_offset": 0.36,
        "lens_diameter": 0.15,
    }
}

PRESET_ENUM_ITEMS = [(k, k, f"Profile for {k}") for k in FIXTURE_PRESETS.keys()]
